// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL62EIxcyf-xmM5SiZVE5juRaRezdAsjk',
    appId: '1:165494950138:web:f460839f32e21a8710e143',
    messagingSenderId: '165494950138',
    projectId: 'flutter-login-d8b83',
    authDomain: 'flutter-login-d8b83.firebaseapp.com',
    storageBucket: 'flutter-login-d8b83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACjADSXvAtNoQcNewqPGuiQjIxtreCS5Y',
    appId: '1:165494950138:android:4fc9a2fcb830139b10e143',
    messagingSenderId: '165494950138',
    projectId: 'flutter-login-d8b83',
    storageBucket: 'flutter-login-d8b83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuRblGEOGACDMVWZWwwZ07GKNKKo7TQ_8',
    appId: '1:165494950138:ios:c89ee0fed4d7581710e143',
    messagingSenderId: '165494950138',
    projectId: 'flutter-login-d8b83',
    storageBucket: 'flutter-login-d8b83.appspot.com',
    iosClientId: '165494950138-b239ol1ms7v3mhid6la95e9sj7c244ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuRblGEOGACDMVWZWwwZ07GKNKKo7TQ_8',
    appId: '1:165494950138:ios:b98f1cf7d15a761410e143',
    messagingSenderId: '165494950138',
    projectId: 'flutter-login-d8b83',
    storageBucket: 'flutter-login-d8b83.appspot.com',
    iosClientId: '165494950138-jc8mnhhd9hkqbsv3ja3k41o5kpv841kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4.RunnerTests',
  );
}
